### PR TITLE
let numPages to be used out of library and change event of property change

### PR DESCRIPTION
**Pull request by prsolucoes**
Fixes:

- let "num pages" to be used out of library
- change event of "property change" to prevent infinite loop
- fixe a bug when activity don't have action bar

### CODE REVIEW

**Comment by mickael-menu** [comment]
@prsolucoes Hi, thank you for your contribution 👍 
I extracted and merged your action bar fix in this commit: https://github.com/readium/r2-navigator-kotlin/commit/1b65c15cf7c52af12ee5bb90443e138c657f0af9

However for the rest, we wan't to think carefully before exposing new APIs publicly. Can you explain a bit more your use cases, and why you made these changes:
* Added an `onPagePropertyChanged` event
* Exposed `R2WebView.numPages`

Thanks again

**Comment by prsolucoes** [comment]
Hi,

I change it to public because im not using your activity/fragment directly but implement my own.

And when i will copy the code of "override fun onPageSelected(position: Int)" i can't use "currentFragment.webView.numPages" because it is internal and not public.

The property changed was create to separate logic between change a property and page loaded. Today you are sending a callback of page loaded when a property change. On our application is hard detect using the original way if the page was really reloaded or only a property changed. With the new callback you can let the person that is implementing the reader choose what he will do when property change.

Thanks.

**Comment by mickael-menu** [comment]
Thanks for your feedback.

> I change it to public because im not using your activity/fragment directly but implement my own.
> 
> And when i will copy the code of "override fun onPageSelected(position: Int)" i can't use "currentFragment.webView.numPages" because it is internal and not public.

I'm not very familiar with this area in the code, but it looks to me that you need `numPages` to go to the last page in the webview.

```kotlin
                if (preferences.getBoolean(SCROLL_REF, false)) {
                    if (currentPagerPosition < position) {
                        // handle swipe LEFT
                        currentFragment?.webView?.scrollToStart()
                    } else if (currentPagerPosition > position) {
                        // handle swipe RIGHT
                        currentFragment?.webView?.scrollToEnd()
                    }
                } else {
                    if (currentPagerPosition < position) {
                        // handle swipe LEFT
                        currentFragment?.webView?.setCurrentItem(0, false)
                    } else if (currentPagerPosition > position) {
                        // handle swipe RIGHT
                        currentFragment?.webView?.apply {
                            setCurrentItem(numPages - 1, false)
                        }
                    }
                }
```

Would that help instead if we have `R2WebView.goToStart()` and `R2WebView.goToEnd()`, which would do internally something like:

```kotlin
fun goToEnd() {
    if (preferences.getBoolean(SCROLL_REF, false)) {
        scrollToEnd()
    } else {
        currentFragment?.webView?.setCurrentItem(numPages - 1, false)
    }
}
```
and then in the Activity, you can do:

```kotlin
currentFragment?.webView?.let { webView ->
    if (currentPagerPosition < position) {
        webView.goToStart()
    } else if (currentPagerPosition > position) {
        webView.goToEnd()
    }
}
```

> On our application is hard detect using the original way if the page was really reloaded or only a property changed.

I understand what you mean. Right now `onPageLoaded()` is broadcasted in `setProperty` to refresh the highlights after the layout changed. But this is not good because we can't know when a page actually finished loading. I think we can add a `onPageLayoutChanged()` event instead, in `setProperty`.

**Comment by prsolucoes** [comment]
Hi,

Im my case i need the amount of pages "currentFragment.webView.numPages" to send to one place or other.

The name of event is not important to me, but the split of event, since it is different.

Thanks.

**Comment by mickael-menu** [comment]
> Im my case i need the amount of pages "currentFragment.webView.numPages" to send to one place or other.

Could you share your code using `numPages` right now? I'm trying to understand why you need it exactly.

**Comment by aferditamuriqi** [comment]
some clarification here about the R2 Webview. This webview is inspired entirely by the ViewPager.  you can find numpages in the ViewPager as well. it's solely used for internal purposes within the webview to mimick the swiping capabilities of the ViewPager. I would not recommend making these internal properties open or public, but instead, if there is additional information needed, those should be added through other means.  the R2 WebViiew and R2 Basic WebView should not be modified as a first solution for accessing internal information. 
I must add the numpages and other values within the webview might not really be the information you're looking for, and changing those to fit the current need might jeopardize the original purpose.

**Comment by prsolucoes** [comment]
Im using to change page, o one side or other:

```
resourcePager.addOnPageChangeListener(object : ViewPager.OnPageChangeListener {

            override fun onPageScrollStateChanged(state: Int) {
                Logger.d("[ReaderReadium2Fragment : onPageScrolled] State: $state")
            }

            override fun onPageScrolled(
                position: Int,
                positionOffset: Float,
                positionOffsetPixels: Int
            ) {
                Logger.d("[ReaderReadium2Fragment : onPageScrolled] Position: $position, PositionOffset: $positionOffset, PositionOffsetPixels: $positionOffsetPixels")
            }

            override fun onPageSelected(position: Int) {
                Logger.d("[ReaderReadium2Fragment : onPageSelected] Position: $position")

                onBeforePageSelected(position)

                pagerPosition = 0

                val currentFragment = ((resourcePager.adapter as R2PagerAdapter).mFragments.get(
                    (resourcePager.adapter as R2PagerAdapter).getItemId(resourcePager.currentItem)
                )) as? R2EpubPageFragment

                if (preferences.getBoolean(SCROLL_REF, false)) {
                    if (currentPagerPosition < position) {
                        // handle swipe LEFT
                        currentFragment?.webView?.scrollToStart()
                    } else if (currentPagerPosition > position) {
                        // handle swipe RIGHT
                        currentFragment?.webView?.scrollToEnd()
                    }
                } else {
                    if (currentPagerPosition < position) {
                        // handle swipe LEFT
                        currentFragment?.webView?.setCurrentItem(0, false)
                    } else if (currentPagerPosition > position) {
                        // handle swipe RIGHT
                        currentFragment?.webView?.setCurrentItem(
                            currentFragment.webView.numPages - 1,
                            false
                        )
                    }
                }

                currentPagerPosition = position
            }
        })
```

**Comment by mickael-menu** [comment]
I agree with Aferdita, we should not expose internals but address use cases.

@prsolucoes From the code you shared, it looks like the solution I described in https://github.com/readium/r2-navigator-kotlin/pull/112#issuecomment-614777249 should work.

Your code would then look like:

```kotlin
override fun onPageSelected(position: Int) {
    Logger.d("[ReaderReadium2Fragment : onPageSelected] Position: $position")

    onBeforePageSelected(position)

    pagerPosition = 0

    val currentFragment = ((resourcePager.adapter as R2PagerAdapter).mFragments.get(
        (resourcePager.adapter as R2PagerAdapter).getItemId(resourcePager.currentItem)
    )) as? R2EpubPageFragment

    if (currentPagerPosition < position) {
        currentFragment?.webView?.goToStart()
    } else if (currentPagerPosition > position) {
        currentFragment?.webView?.goToEnd()
    }

    currentPagerPosition = position
}
```

Could you tell us a bit more about why you decided to create your own `Activity` instead of using `R2EpubActivity`? This will help us improve the toolkit.

**Comment by prsolucoes** [comment]
Some methods can be implemented too:

- goToStart
- goToEnd
- goToNext
- goToPrevious

**Comment by prsolucoes** [comment]
> I agree with Aferdita, we should not expose internals but address use cases.
> 
> @prsolucoes From the code you shared, it looks like the solution I described in [#112 (comment)](https://github.com/readium/r2-navigator-kotlin/pull/112#issuecomment-614777249) should work.
> 
> Your code would then look like:
> 
> ```kotlin
> override fun onPageSelected(position: Int) {
>     Logger.d("[ReaderReadium2Fragment : onPageSelected] Position: $position")
> 
>     onBeforePageSelected(position)
> 
>     pagerPosition = 0
> 
>     val currentFragment = ((resourcePager.adapter as R2PagerAdapter).mFragments.get(
>         (resourcePager.adapter as R2PagerAdapter).getItemId(resourcePager.currentItem)
>     )) as? R2EpubPageFragment
> 
>     if (currentPagerPosition < position) {
>         currentFragment?.webView?.goToStart()
>     } else if (currentPagerPosition > position) {
>         currentFragment?.webView?.goToEnd()
>     }
> 
>     currentPagerPosition = position
> }
> ```
> 
> Could you tell us a bit more about why you decided to create your own `Activity` instead of using `R2EpubActivity`? This will help us improve the toolkit.

Hi,

My project already have an activity. We have four readers in our project and the readers are fragments (epub, pdf etc). So we have only one activity that extends our base activity and the body/content is a fragment depending of the file type.

Our base activity has a lot of methods that we need for our project. So i cant use your activity. Instead i reimplement it on fragment and pass all activity events to that fragment.

**Comment by mickael-menu** [comment]
@prsolucoes 

> My project already have an activity. We have four readers in our project and the readers are fragments (epub, pdf etc). So we have only one activity that extends our base activity and the body/content is a fragment depending of the file type.

Thanks for your feedback, [we're considering moving to `Fragment` in the near future](https://github.com/readium/r2-navigator-kotlin/issues/115).

**Comment by mickael-menu** [comment]
@prsolucoes I'll close this PR for now, but feel free to submit another PR with the changes we mentioned in our discussion, if you need.

**Pull request closed without merging**
